name: Docker Image CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Checkout kodu
      - name: Checkout code
        uses: actions/checkout@v4

      # Krok 2: Budowanie obrazu Docker
      - name: Build Docker image
        run: docker build -t flask_app:1.0.0 .

      # Krok 3: Uruchomienie aplikacji w kontenerze
      - name: Test the app inside Docker image
        run: docker run -d -p 5000:5000 flask_app:1.0.0

      # Krok 4: Uruchomienie testów (jeśli masz jakieś testy w aplikacji)
      - name: Run tests
        run: docker exec <container_id> pytest  # Zastąp <container_id> rzeczywistym ID kontenera

      # Krok 5: Publikowanie obrazu Docker do repozytorium
      - name: Publish the image
        run: echo "Publishing the image to a public repository"
