name: CI

on:
    push:
     branches: ["main"]
    pull_request:
     branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Pull repo
          uses: actions/checkout@v4
        - name: hello world
          run: echo "hello world"
        - name: Log in to DockerHub
          uses: docker/login-action@v2
          with:
           username: ${{ secrets.D_NAME }}
           password: ${{ secrets.D_PASS }}
        - name: Build and tag Docker image
          run: |
           docker build -t project:1.0.0 .
        - name: Push Docker image
          run: |
           docker tag project:1.0.0 jaroslawlyczak/project:1.0.0
           docker push jaroslawlyczak/project:1.0.0
