name: Docker Image CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Checkout kodu
      - name: Checkout code
        uses: actions/checkout@v4
      # Krok 2: Budowanie obrazu Docker
      - name: Build Docker image
        run: docker build -t project:1.0.0 .
      # Krok 3: Uruchomienie kontenera i zapisanie ID
      - name: Run Docker container and save container ID
        id: run_container
        run: |
          container_id=$(docker run -d -p 8080:5000 project:1.0.0)
          echo "Container ID: $container_id"
          echo "CONTAINER_ID=$container_id" >> $GITHUB_ENV
      # Krok 4: Uruchomienie testów wewnątrz kontenera
      - name: Run tests inside Docker container
        run: echo "Test"
      # Krok 5: Publikowanie obrazu (opcjonalnie)
      - name: Publish the Docker image
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.D_NAME }}
           password: ${{ secrets.D_PASS }}

      - name: Push Docker image
        run: |
           docker build -t project:1.0.0 .
      - name: Push Docker image
        run: |
          docker tag project:1.0.0 jareklyczak/project:1.0.0
          docker push jareklyczak/project:1.0.0

